### ISSUE TITLE
Virtual Desktop Bar doesn't detect WPS Office and OnlyOffice

### ISSUE THREAD

**Issue by Prayag2** [wsdfhjxc/virtual-desktop-bar#51] opened 2021-01-20 14:31 UTC
I am using Virtual Desktop Office with these settings enabled-
1) Dynamic Virtual Desktop
2) The name of the current desktop should be the name of the active window

All applications work fine but it won't detect WPS Office and OnlyOffice and virtual desktop is not created automatically. Here's a screenshot- 
![SS_2021-01-20_20-01-01](https://user-images.githubusercontent.com/39525869/105188806-49e71f80-5b5a-11eb-97af-355fe56b8844.png)

**Comment by wsdfhjxc** [comment] 2021-01-20 18:02
Is this the most recent git version?

**Comment by Prayag2** [comment] 2021-01-22 06:50
Yes.

**Comment by Prayag2** [comment] 2021-01-28 09:35
Please fix this issue!

**Comment by wsdfhjxc** [comment] 2021-01-28 20:48
Check out the latest changes. It should be fixed.

**Comment by Prayag2** [comment] 2021-01-29 05:56
Thanks :)

**Comment by Prayag2** [comment] 2021-01-29 08:38
It is detecting all applications now (including utility windows like "configure virtual desktop") but setting the name of the current desktop to the name of the active window isn't working. The name is "Plasma" for all desktops.
![SS_2021-01-29_14-07-14](https://user-images.githubusercontent.com/39525869/106251706-5135b980-623b-11eb-900a-b38f16b16692.png)
![SS_2021-01-29_14-06-49](https://user-images.githubusercontent.com/39525869/106251724-55fa6d80-623b-11eb-9d31-2da796851c47.png)

**Comment by Prayag2** [comment] 2021-01-31 05:54
Please, I absolutely love virtual desktop bar! There's no other widget like this, so please fix it!

**Comment by wsdfhjxc** [comment] 2021-01-31 21:37
That's weird. I can't reproduce the issue. The button labels are incorrect, but can you tell me what is displayed by the tooltips? Are they also incorrectly displaying "No windows", or are windows actually listed there? That information would be helpful.

**Comment by Prayag2** [comment] 2021-02-01 05:36
![SS_2021-02-01_11-05-33](https://user-images.githubusercontent.com/39525869/106418971-7285e800-647d-11eb-948d-bcb7c57348b3.png)
The tooltips are saying "Plasma, {application name}". In this screenshot, I've opened WPS Presentation and the tooltips are saying, "Plasma, WPS Presentation"

**Comment by wsdfhjxc** [comment] 2021-02-01 19:15
Please check out the latest changes.

**Comment by Prayag2** [comment] 2021-02-02 06:39
Okay! Thanks :)
And also, sorry to bother you again and again!

**Closed** 2021-02-02 06:53 UTC
Labels: bug
